PawCare-1/PawCare/urls.py
from django.contrib import admin
from django.urls import path ,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.views import HomeView,ColaboradoresView,SomosView,ServicioView
from applications.users.views import UserRegisterView
from applications.users.urls import auth_views 
from applications.users.forms import MySetPasswordForm



urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.users.urls')),

    re_path('', include('applications.home.urls')),

    re_path('', include('applications.administracion.urls')),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('users/',include('applications.users.urls',namespace='users')),
    # path('administracion/',include('applications.administracion.urls',namespace='administracion')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PawCare-1/applications/administracion/urls.py
from django.urls import path
from .views import *

app_name = "admin_app"

urlpatterns = [
    path('colab/', ListColaboradores.as_view(),name='colaboradores'),
    path('list_colab_admin/', ListColaboradores_admin.as_view(), name='colaboradores_admin'),
    path('list_colab_admin/<id>', ListColaboradores2_admin.as_view(), name='colaboradores_admin_s'),
    path('crear_colaborador/',AddColaboradores_admin.as_view(), name='crear_colaborador'),
    path('colaborador_modificar/<int:pk>', ModificarColab_admin.as_view(),name='colaborador_modificar'),
    

]

PawCare-1/applications/home/urls.py
from django.urls import path
from .views import *

app_name = "home_app"

urlpatterns = [
    path('',HomeView.as_view(),name='home',),
    path('colaboradores/',ColaboradoresView.as_view(),name='colaboradores',),
    path('servicios/',ServicioView.as_view(),name='servicios',),
    path('somos/',SomosView.as_view(),name='somos',),

    path('base/',BaseView.as_view(),name='base',),


]

PawCare-1/applications/users/urls.py
from django.urls import path


from django.contrib.auth import views as auth_views
from .views import *

from .forms import UserPasswordResetForm
from .views import View
from . import views
app_name ="users_app"


urlpatterns = [
    path('registro/', UserRegisterView.as_view(),name='user_register'),
    path('login/', LoginUser.as_view(),name='user_login'),
    path('logout/', LogoutView.as_view(),name='user_logout'),
    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),
    path('users/<username>', PerfilDetailView.as_view(),name='profile'),
    path('calendario/',CalendarioView.as_view(), name= 'calendario'),
    path('horas/',Addhoras.as_view(), name= 'horas'),
    path('list_mascota/', ListMascotas.as_view(), name='mascota'),
    path('list_mascota/<id>', ListMascotas2.as_view(), name='mascota'),
    path('crear_mascota/',AddMascota.as_view(), name='crear_mascota'),
    path('mascota_modificar/<int:pk>', ModificarMascota.as_view(),name='mascota_modificar'),
    path('mascota_eliminar/<int:pk>', MascotaDeleteView.as_view(),name='mascota_eliminar'),
    path('update/<int:pk>', PerfilUpdateView.as_view(),name='update'),

    path('list_horas/', ListCronogramaDisponibles.as_view(), name='horaseliminar'),
    path('cronograma_eliminar/<int:pk>', CronogramaDeleteView.as_view(),name='cronograma_eliminar'),

    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),

  

    path('servicios/<int:id>', ListCuidadores3.as_view(),name='cuidadores3'),
    
    path('servicios/<id>', ReservaRegisterView.as_view(),name='cuidadores3'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', form_class=UserPasswordResetForm,html_email_template_name ='users/password_reset_email.html'), name='password_reset'),
    path('api/mascota/por-usuario/', ListMascotaUser.as_view(),name='mascota-mascota-by-user'),

    path('vista_reserva/',ClienteResevarView.as_view(), name= 'vista_reserva'),

    path('list_user_admin/', ListUser.as_view(), name='usuarios_admin'),
    path('list_user_admin/<id>', ListUser2.as_view(), name='usuarios_admin_s'),
    path('user_modificar/<int:pk>', ModificarUser_admin.as_view(),name='user_modificar'),


    path('list_servicio_admin/', ListServicios.as_view(), name='servicios_admin'),
    path('list_servicio_admin/<id>', ListServicios2_admin.as_view(), name='servicios_admin_s'),
    path('crear_servicios/',AddServicios_admin.as_view(), name='crear_servicio'),
    path('servicio_modificar/<int:pk>', ModificarServicio_admin.as_view(),name='servicio_modificar'),
    path('servicio_eliminar/<int:pk>', ServicioDeleteView.as_view(),name='servicio_eliminar'),

    path('list_especie_admin/', ListEspecies.as_view(), name='especie_admin'),
    path('list_especie_admin/<id>', ListEspecies2_admin.as_view(), name='especie_admin_s'),
    path('crear_especie/',AddEspecies_admin.as_view(), name='crear_especie'),
    path('especie_modificar/<int:pk>', ModificarEspecie_admin.as_view(),name='especie_modificar'),
    path('especie_eliminar/<int:pk>', EspecieDeleteView.as_view(),name='especie_eliminar'),

    path('reservar_cuidador/<int:cronograma_id>', views.reservar_cuidador, name='reservar_cuidador'),
    
    path('list_horas_user/', HorasporUserList.as_view(), name='horas_user'),

    path('list_horas_realizadas_user/', HorasRealizadasporUserList.as_view(), name='horas_user_realizadas'), #esta

    path('cancelar_cuidador/<int:idReserva>', views.cancelar_cuidador, name='cancelar_cuidador'),
    path('finalizar_reserva/<int:idReserva>', views.finalizar_reserva, name='finalizar_reserva'),
    #path('rating_modal/', views.rating_modal , name='rating_modal'),
    path('rating_modal/', Calificacion.as_view() , name='rating_modal'),
    path('finalizar_reserva/<int:idReserva>/', views.finalizar_reserva, name='finalizar_reserva'),

    path('guardar_calificacion/', views.guardar_calificacion, name='guardar_calificacion'),
    #path('calcular_promedio_calificacion/', views.calcular_promedio_calificacion, name='calcular_promedio_calificacion'),
]

PawCare-1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PawCare</title>
    <link rel="icon" href="{% static 'img/manolg.png' %}">
    <link href="{% static 'css/estilos.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">

    <!-- jQuery library -->
    <script  src="{% static '/jquery-3.7.0.min.js' %} "></script> 
    <!-- Latest compiled JavaScript -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'fontawesome-free-6.4.0-web/css/all.min.css' %}">

    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 {% endcomment %}



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light col-12">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu">
                <span class="navbar-toggler-icon"></span>
            </button>
                <a class="navbar-brand grow" href="{% url 'home_app:home' %}">
                    <img src="{% static 'img/naranja.png' %}" onclick=""  id="manonaranja" style=" width: auto; height: 100px; margin-left: 20px;">
                </a>
                <div class="collapse navbar-collapse" id="menu">   
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class=" resaltar nav-link" id="inicio" href="{% url 'home_app:home' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="resaltar1 nav-link" id="somos" href="{% url 'home_app:somos' %}">Quienes somos</a>
                        </li>
                        <li class="nav-item">
                            <a class=" resaltar nav-link" id="colaboradores" href="{% url 'admin_app:colaboradores' %}">Colaboradores</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class=" resaltar1 nav-link" id="servicios" href="{% url 'home_app:servicios' %}">Servicios</a>
                        </li>
                        {% endif %}

                        <!--AGREGUE ESTE BLOQUE PARA LOGIN-->
                        
                       
                       
                        {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a type="button" class="btn btn-outline-danger me-2"  href="{% url 'users_app:user_logout' %}">Cerrar Sesión</a>
                        </li>

    <!--                    <li class= "nav-item">   
                            <a class="nav-link"  href="{% url 'users:profile' user.username %}">Bienvenido {{user.username | upper}} :)</a>   

                        </li> -->

                        <div class="btn-group" >
                            <div class="dropdown">
                                <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                                    Bienvenido {{user.username | upper}} :)
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class=" resaltar1 nav-link dropdown-item fa-solid fa-user" href="{% url 'users:profile' user.username  %}">Mi Perfil</a></li>
                                
                                
                                {%if request.user.categoria == '1' %}
                                
                                <li><a class="resaltar1 nav-link dropdown-item fa-solid fa-paw" href="{% url 'users:mascota'  %}">Mis Mascotas</a></li>
                               
                                <li><a class="resaltar1 nav-link dropdown-item fa-solid fa-clock " href="{% url 'users:horas_user'  %}">Mis reservas</a></li>

                                <li><a class="resaltar1 nav-link dropdown-item  fa-solid fa-clock " href="{% url 'users:horas_user_realizadas'  %}">Historial de Atencion</a></li>

                               
                                
                                {% endif %}   
                                </ul>
                                
                                
                            </div>
                          <div>
                          
                        {%if request.user.categoria == '2' %}
                        <li class= "nav-item">   
                            
                            <a class="nav-link fa-solid fa-calendar-days fa-2xl"  href="{% url 'users:calendario'  %}"></a>   

                        </li>
                        {% endif %}
                      

                         {%if request.user.categoria == '3' %} 
                        {% comment %} <li class= "nav-item">   
                            <a class="nav-link"  href="{% url 'admin_app:colaboradores_admin'  %}">Administracion </a>  

                        </li> {% endcomment %}
                        <div class="btn-group" >
                            <div class="dropdown">
                                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                                    Administracion
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li><a class="resaltar1 nav-link dropdown-item fa-solid fa-user-group" href="{% url 'admin_app:colaboradores_admin'  %}">Admin_Colaboradores</a></li>
                
                                <li><a class="resaltar1 nav-link dropdown-item fa-solid fa-user-group" href="{% url 'users_app:usuarios_admin'  %}">Admin_Usuarios</a></li>
                                
                                <li><a class="resaltar1 nav-link dropdown-item  fa-solid fa-bell-concierge" href="{% url 'users_app:servicios_admin'  %}">Admin_Servicios</a></li>
                                
                                <li><a class="resaltar1 nav-link dropdown-item fa-solid fa-dog" href="{% url 'users_app:especie_admin'  %}">Admin_Especies</a></li>
                             
                                </ul>
                            </div>
                          <div>

                         {% endif %} 

                        {% else %}

                        <li class="nav-item" >
                            <a type="button" class="btn btn-outline-primary me-2"  href="{% url 'users_app:user_login'  %}">Iniciar Sesión</a>
                        </li>

                        <li class="nav-item" >
                            <a type="button" class="btn btn-outline-danger me-2" href="{% url 'users_app:user_register' %}">Registrarse</a>
                        </li>

                        {% endif %}
                        
                    
                        <!---->                       



                    </ul>
                </div>
        </nav>
    </header>

    <main class="contenido">
        {% block content %}

        {% endblock %}

    </main>

    <footer class="bcolor">
        <footer class="text-center text-lg-start text-muted border-top">           
            <section class="">
                <div class="container container-fluid text-center text-md-start mt-5" style="height: 100%;">
                    <div class="row row-cols-md-4 mt-3">
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 justify-content-center">
                            <!-- Content -->
                            <img src="{% static 'img/logofoot.png' %}" class="rounded-circle"
                                style="width: auto; height: 150px "></img>
                        </div>
                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <ul style="list-style: none;">
                                <li>
                                    <h7 class="text-uppercase text-center fw-bold mb-4">
                                        
                                            <a href="/" class="nolink nolinkh">PawCare</a>
                                    </h7>
                                </li>
                                <br>
                                <li>
                                    <h7 class="text-uppercase text-center fw-bold mb-4">
                                       
                                        <a href="{% url 'home_app:somos' %}" class="nolink nolinkh">Quienes Somos</a>
                                    </h7>
                                </li>
                                <br>
                                <li>
                                    <h7 class="text-uppercase text-center fw-bold mb-4">
                                        
                                        <a href="{% url 'home_app:servicios' %}" class="nolink nolinkh">Servicios</a>
                                    </h7>
                                </li>
                                <br>
                                <li>
                                    <h7 class="text-uppercase text-center fw-bold mb-4">
                                        <a href="{% url 'admin_app:colaboradores' %}" class="nolink nolinkh">Colaboradores</a>
                                    </h7>
                                </li>        
                            </ul>
                        </div>
                                                    
                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h7 class="text-uppercase text-center fw-bold mb-4">
                                Contacto
                            </h7>
                            <p>
                                <img src="{% static 'img/geoazul.png' %}" style="width: auto; height: 20px"></img>
                                Camino Melipilla
                                1432,
                                Santiago
                            </p>
                            <p>
                                <img src="{% static 'img/correoazul.png' %}" style="width: auto; height: 20px"></img>
                                contacto@pawcare.cl
                            </p>
                            <p>
                                <img src="{% static 'img/fonoazul.png' %}" style="width: auto; height: 20px"></img> + 56
                                9 8327 4639</p>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h7 class="text-uppercase text-center fw-bold mb-4">
                                Redes Sociales
                            </h7>
                            <p>
                                <a href="/" class="me-4 text-reset">
                                    <img src="{% static 'img/facebook.png' %}"style="width: auto; height: 30px"></img>
                                </a>
                            </p>
                            <p>
                                <a href="/" class="me-4 text-reset">
                                    <img src="{% static 'img/instagram.png' %}"style="width: auto; height: 30px"></img>
                                </a>
                            </p>
                            <p>
                                <a href="/" class="me-4 text-reset">
                                    <img src="{% static 'img/twitter.png' %}"style="width: auto; height: 30px"></img>
                                </a>
                        </div>
                        <!-- Grid column -->
                    </div>
                    <!-- Grid row -->
                </div>
            </section>
            <!-- Section: Links  -->
            <section class="">
            <!-- Copyright -->
            <div id="copyright" class="text-center p-4" style="background-color: rgb(41, 41, 41);">
                <h6 style="color: aliceblue;">Felipe Garcia - Felipe Reyes - Verónica Torres © Portafolio 2023 Copyright: PawCare</h6>
                <!--<h6><a class="text-reset fw-bold" href="">PawCare</a></h6>-->
            </div>
            <!-- Copyright -->
        </footer>
    </footer>



</body>
</html>