PawCare-1/PawCare/urls.py
from django.contrib import admin
from django.urls import path ,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.views import HomeView,ColaboradoresView,SomosView,ServicioView
from applications.users.views import UserRegisterView
from applications.users.urls import auth_views 
from applications.users.forms import MySetPasswordForm



urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.users.urls')),

    re_path('', include('applications.home.urls')),

    re_path('', include('applications.administracion.urls')),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('users/',include('applications.users.urls',namespace='users')),
    # path('administracion/',include('applications.administracion.urls',namespace='administracion')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PawCare-1/applications/administracion/urls.py
from django.urls import path
from .views import *

app_name = "admin_app"

urlpatterns = [
    path('colab/', ListColaboradores.as_view(),name='colaboradores'),
    path('list_colab_admin/', ListColaboradores_admin.as_view(), name='colaboradores_admin'),
    path('list_colab_admin/<id>', ListColaboradores2_admin.as_view(), name='colaboradores_admin_s'),
    path('crear_colaborador/',AddColaboradores_admin.as_view(), name='crear_colaborador'),
    path('colaborador_modificar/<int:pk>', ModificarColab_admin.as_view(),name='colaborador_modificar'),
    

]

PawCare-1/applications/users/urls.py
from django.urls import path


from django.contrib.auth import views as auth_views
from .views import *

from .forms import UserPasswordResetForm
from .views import View
from . import views
app_name ="users_app"


urlpatterns = [
    path('registro/', UserRegisterView.as_view(),name='user_register'),
    path('login/', LoginUser.as_view(),name='user_login'),
    path('logout/', LogoutView.as_view(),name='user_logout'),
    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),
    path('users/<username>', PerfilDetailView.as_view(),name='profile'),
    path('calendario/',CalendarioView.as_view(), name= 'calendario'),
    path('horas/',Addhoras.as_view(), name= 'horas'),
    path('list_mascota/', ListMascotas.as_view(), name='mascota'),
    path('list_mascota/<id>', ListMascotas2.as_view(), name='mascota'),
    path('crear_mascota/',AddMascota.as_view(), name='crear_mascota'),
    path('mascota_modificar/<int:pk>', ModificarMascota.as_view(),name='mascota_modificar'),
    path('mascota_eliminar/<int:pk>', MascotaDeleteView.as_view(),name='mascota_eliminar'),
    path('update/<int:pk>', PerfilUpdateView.as_view(),name='update'),

    path('list_horas/', ListCronogramaDisponibles.as_view(), name='horaseliminar'),
    path('cronograma_eliminar/<int:pk>', CronogramaDeleteView.as_view(),name='cronograma_eliminar'),

    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),

  

    path('servicios/<int:id>', ListCuidadores3.as_view(),name='cuidadores3'),
    
    path('servicios/<id>', ReservaRegisterView.as_view(),name='cuidadores3'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', form_class=UserPasswordResetForm,html_email_template_name ='users/password_reset_email.html'), name='password_reset'),
    path('api/mascota/por-usuario/', ListMascotaUser.as_view(),name='mascota-mascota-by-user'),

    path('vista_reserva/',ClienteResevarView.as_view(), name= 'vista_reserva'),

    path('list_user_admin/', ListUser.as_view(), name='usuarios_admin'),
    path('list_user_admin/<id>', ListUser2.as_view(), name='usuarios_admin_s'),
    path('user_modificar/<int:pk>', ModificarUser_admin.as_view(),name='user_modificar'),


    path('list_servicio_admin/', ListServicios.as_view(), name='servicios_admin'),
    path('list_servicio_admin/<id>', ListServicios2_admin.as_view(), name='servicios_admin_s'),
    path('crear_servicios/',AddServicios_admin.as_view(), name='crear_servicio'),
    path('servicio_modificar/<int:pk>', ModificarServicio_admin.as_view(),name='servicio_modificar'),
    path('servicio_eliminar/<int:pk>', ServicioDeleteView.as_view(),name='servicio_eliminar'),

    path('list_especie_admin/', ListEspecies.as_view(), name='especie_admin'),
    path('list_especie_admin/<id>', ListEspecies2_admin.as_view(), name='especie_admin_s'),
    path('crear_especie/',AddEspecies_admin.as_view(), name='crear_especie'),
    path('especie_modificar/<int:pk>', ModificarEspecie_admin.as_view(),name='especie_modificar'),
    path('especie_eliminar/<int:pk>', EspecieDeleteView.as_view(),name='especie_eliminar'),

    path('reservar_cuidador/<int:cronograma_id>', views.reservar_cuidador, name='reservar_cuidador'),
    
    path('list_horas_user/', HorasporUserList.as_view(), name='horas_user'),

    path('list_horas_realizadas_user/', HorasRealizadasporUserList.as_view(), name='horas_user_realizadas'), #esta

    path('cancelar_cuidador/<int:idReserva>', views.cancelar_cuidador, name='cancelar_cuidador'),
    path('finalizar_reserva/<int:idReserva>', views.finalizar_reserva, name='finalizar_reserva'),
    #path('rating_modal/', views.rating_modal , name='rating_modal'),
    path('rating_modal/', Calificacion.as_view() , name='rating_modal'),
    path('finalizar_reserva/<int:idReserva>/', views.finalizar_reserva, name='finalizar_reserva'),

    path('guardar_calificacion/', views.guardar_calificacion, name='guardar_calificacion'),
    #path('calcular_promedio_calificacion/', views.calcular_promedio_calificacion, name='calcular_promedio_calificacion'),
]

PawCare-1/applications/administracion/models.py
from django.db import models
from .managers import ColabManager
# Create your models here.


#Esta tabla debe ser llanada por nosotros
class Colaboradores(models.Model):

    IS_PUBLISHED_CHOICES = [
        ('No','No '), 
        ('Si', 'Si')]

    title = models.CharField(max_length= 100, verbose_name='Nombre del Patrocinador')
    image = models.ImageField(upload_to='colaboradores' ,null=True, blank=True, verbose_name='Imagen del Patrocinador')
    content = models.TextField(verbose_name='Descripccion del Colaborador')
    descuento = models.CharField(max_length=100,null=True,verbose_name='Codigo de descuento') 
    url = models.URLField(max_length=350, blank=True, null=True, verbose_name='Enlace' , default= 'http://127.0.0.1:8000/colab/')
    published = models.BooleanField(default=True, verbose_name='Publicado')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha en las que se nos unio')

    class Meta:
        verbose_name = 'Colaborador'
        verbose_name_plural = 'Colaboradores'
        ordering = ['-created']

    objects = ColabManager()

    def __str__(self):
        return self.title

PawCare-1/applications/administracion/forms.py
from django import forms
from .models import Colaboradores

class ColaboradorForm(forms.ModelForm):

    class Meta:
        model= Colaboradores
        fields = ['title','image','content','descuento','url','published']
        labels = {
            'title':'Ingrese el nombre del Colaborador',
            'image':'Imagen del Colaborador',
            'content':'Descripccion del Colaborador',
            'descuento':'Ingrese el codigo de descuento del Colaborador',
            # 'url':'Ingrese el sitio web del Colaborador',
            'published':'Publicar',
        }
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'descuento':forms.TextInput(attrs={'class':'form-control'}),
            'url':forms.TextInput(attrs={'class':'form-control'}),
            # 'published':forms.BooleanField(required=True,label='Deseas ocultarlo',label_suffix='',initial=True,error_messages={'required':'Porfavor selecciona un estado'}),

            # 'url':forms.URLField(),
            # 'published':forms.BooleanField(),
        }

PawCare-1/applications/administracion/views.py
import dataclasses
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy ,reverse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic.base import TemplateView

from .models import Colaboradores
from .forms import ColaboradorForm
# Create your views here.
class ListColaboradores(ListView):
    context_object_name= 'lista_colaboradores'
    template_name= 'home/colab.html'
    

    def get_queryset(self):
        return Colaboradores.objects.listar_colaboradores()
    
    def get_queryset(self):
        return Colaboradores.objects.filter(published=True)
    
class ListColaboradores_admin(LoginRequiredMixin,ListView):
    context_object_name= 'lista_colaboradores'
    template_name= 'administracion/list_colab.html'
    login_url = reverse_lazy('users_app:user_login')

    def get_queryset(self):
        return Colaboradores.objects.listar_colaboradores()
    
class ListColaboradores2_admin(LoginRequiredMixin,ListView):
    context_object_name= 'lista_colaboradores'
    template_name= 'administracion/list_colab.html'
    login_url = reverse_lazy('users_app:user_login')

    def get_queryset(self):
        return Colaboradores.objects.listar_colaboradores()
    

class AddColaboradores_admin(LoginRequiredMixin,FormView):
    template_name= 'administracion/colaboradorCrear.html'
    form_class = ColaboradorForm
    success_url =reverse_lazy('admin_app:colaboradores_admin') 
    login_url = reverse_lazy('users_app:user_login')

    def form_valid(self, form):
        Colaboradores.objects.create(
            title=form.cleaned_data['title'],
            image=form.cleaned_data['image'],
            content=form.cleaned_data['content'],
            descuento=form.cleaned_data['descuento'],
            url=form.cleaned_data['url'],
            published=False,
            created=date.today(),
        )

        return super(AddColaboradores_admin, self).form_valid(form)
    
class ModificarColab_admin(LoginRequiredMixin,UpdateView):
    model= Colaboradores
    form_class= ColaboradorForm 
    template_name='administracion/colaboradorModificar.html'
    success_url=reverse_lazy('admin_app:colaboradores_admin_s')
    login_url = reverse_lazy('users_app:user_login')

    def form_invalid(self, form):
        return super().form_invalid(form)
    
    def get_success_url(self):
        return reverse_lazy('admin_app:colaboradores_admin_s',args=[self.object.id]) 

PawCare-1/templates/administracion/colaboradorCrear.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

 <div class="content">
    <div class="col-md-4">
        <a href="{% url 'admin_app:colaboradores_admin'  %}"> Volver</a>
    </div>
</div> 

<div class="container">
    <div class="row">
        <h2>Ingresar Colaborador</h2> 
    </div>
    <br>

        <div class="row">
            <form method="POST" action="#" id="formulario" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.title.label }}
                    {{ form.title }}
                </div>
                 
                <div class="form-group">
                    {{ form.image.label }}
                    {{ form.image }}
                </div>

                <div class="form-group">
                    {{ form.content.label }}
                    {{ form.content }}
                </div>

                <div class="form-group">
                  {{ form.descuento.label }}
                  {{ form.descuento }}
              </div>

              <div class="form-group">
                {{ form.url.label }}
                {{ form.url }}
            </div>

             <div class="form-group">
                {{ form.published.label }} 
                {{ form.published }}
            </div> 

              {% comment %} <div class="form-group">
                  
                {{ Colaborador_Form.published }}
            </div> {% endcomment %}
                <br>
                <div class="row">
                    <div class="col-md">

                        <input type="submit" class="btn btn-primary" value="Crear">
                        <input type="reset" class="btn btn-danger" value="Limpiar">
                        {% comment %} <a href="{% url 'admin_app:colaboradores_admin' form.id %}" class="btn btn-info">Volver</a> {% endcomment %}
                        
                    </div>
                </div>
                
            </form>
        </div>
</div> <br><br>
{% endblock %}

PawCare-1/templates/administracion/especieModificar.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<br>
{% comment %} <div class="content">
    <div class="col-md-4">
        <a href="{% url 'admin_app:colaboradores_admin_s' form.id %}"> Volver</a>
    </div>
</div> {% endcomment %}

<div class="container">
  
     {% if 'ok' in request.GET %} 
         <div class="alert alert-success" role="alert">
            La especie se ha actualizado correctamente 
            <span>
                <a class="btn btn-sm btn-success" href="{% url 'users:especie_admin'  %}" id="">Volver</a>
            </span>
        </div>
    {% endif %} 

<div class="container">
    <div class="row">
        <h2>Modificar Especie</h2> 
    </div>
    <br>

        <div class="row">
            <form method="POST" action="#" id="formulario" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.id.label }}
                    {{ form.id }}
                </div>
                 
                <div class="form-group">
                    {{ form.nombre.label }}
                    {{ form.nombre }}
                </div>

   




                <br>
                <div class="row">
                    <div class="col-md">

                        <input type="submit" class="btn btn-primary" value="Modificar">
                        {% comment %} <a href="{% url 'admin_app:colaboradores_admin' id %}" class="btn btn-info">Volver</a> {% endcomment %}
                        
                    </div>
                </div>
                
            </form>
        </div>
</div> <br><br>
{% endblock %}

PawCare-1/templates/administracion/especiesCrear.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

 <div class="content">
    <div class="col-md-4">
        <a href="{% url 'users_app:especie_admin'  %}"> Volver</a>
    </div>
</div> 

<div class="container">
    <div class="row">
        <h2>Ingresar Especie</h2> 
    </div>
    <br>

        <div class="row">
            <form method="POST" action="#" id="formulario" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.id.label }}
                    {{ form.id }}
                </div>
                 
                <div class="form-group">
                    {{ form.nombre.label }}
                    {{ form.nombre }}
                </div>



              {% comment %} <div class="form-group">
                  
                {{ Colaborador_Form.published }}
            </div> {% endcomment %}
                <br>
                <div class="row">
                    <div class="col-md">

                        <input type="submit" class="btn btn-primary" value="Crear">
                        <input type="reset" class="btn btn-danger" value="Limpiar">
                        {% comment %} <a href="{% url 'admin_app:colaboradores_admin' form.id %}" class="btn btn-info">Volver</a> {% endcomment %}
                        
                    </div>
                </div>
                
            </form>
        </div>
</div> <br><br>
{% endblock %}

PawCare-1/templates/administracion/list_colab.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">

{% comment %} para menu de administracion
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown button
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div> {% endcomment %}

  
<br>
<div class="container">
    <h2 class="titulo">Lista de Colaboradores</h2><br><br>

  
    <a href="{% url 'admin_app:crear_colaborador' %}" class="btn btn-primary btn-info btn-info-hover">Agregar Colaborador</a> <br>
    <table class="table"> <br>
        <thead>
            <tr>
                <th>Nombre del Patrocinador</th>
                <th>Descipccion</th>
                <th>Codigo de descuento</th>
                <th>Link de Patrocinador</th>
                <th>Ingreso</th>
                <th>Se encuentra Publicado</th> 
                
                <th>Foto de la marca</th>
  
            </tr>
        </thead>
        <tbody>
            {% for c in lista_colaboradores %}
            <tr>
                <td>{{c.title}}</td>
                <td>{{c.content}}</td>
                <td>{{c.descuento}}</td>
                <td>{{c.url}}</td>
                <td>{{c.created}}</td>
                <td>{{c.published}}</td>
                <td>
                  {% if c.image %}
                  <img class="imagen-colab" src="{{c.image.url}}" width="100px" height="100px" alt="">
                  {% endif %}
                </td>
                <td><a href="{% url 'admin_app:colaborador_modificar' c.id %}" class="btn btn-primary  btn-info btn-info-hover">Modificar</a></td>
                {% comment %} <td><a href="#" class="btn btn-danger">Eliminar</a></td> {% endcomment %}
            </tr>
            {% endfor %}
        </tbody>
    </table><br>
  </div><br><br>

  
 


{% endblock %}

PawCare-1/templates/administracion/list_especies.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">

<br>
<div class="container">
    <h2 class="titulo">Lista de Especies</h2><br><br>

  
    <a href="{% url 'users_app:crear_especie' %}" class="btn btn-primary btn-info btn-info-hover">Agregar Especie</a> <br>
    <table class="table"> <br>
        <thead>
            <tr>
                <th>Identificador</th>
                <th>Nombre de la especie</th>
                
            </tr>
        </thead>
        <tbody>
            {% for e in lista_especies %}
            <tr>
                <td>{{e.id}}</td>
                <td>{{e.nombre}}</td>

                <td><a href="{% url 'users_app:especie_modificar' e.id %}" class="btn btn-primary  btn-info btn-info-hover">Modificar</a></td>
                <td><a href="{% url 'users_app:especie_eliminar' e.id %}" class="btn btn-danger">Eliminar</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table><br>
  </div><br><br>

  
 


{% endblock %}

PawCare-1/templates/administracion/list_servicios.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">

{% comment %} para menu de administracion
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown button
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div> {% endcomment %}

  
<br>
<div class="container">
    <h2 class="titulo">Lista de Servicios</h2><br><br>

  
    <a href="{% url 'users_app:crear_servicio' %}" class="btn btn-primary btn-info btn-info-hover">Agregar Servicio</a> <br>
    <table class="table"> <br>
        <thead>
            <tr>
                <th>Identificador</th>
                <th>Nombre</th>
                <th>Informacion</th>
  
            </tr>
        </thead>
        <tbody>
            {% for s in lista_servicios %}
            <tr>
                <td>{{s.id}}</td>
                <td>{{s.nombre}}</td>
                <td>{{s.informacion}}</td>

  
                <td><a href="{% url 'users_app:servicio_modificar' s.id %}" class="btn btn-primary  btn-info btn-info-hover">Modificar</a></td>
                <td><a href="{% url 'users_app:servicio_eliminar' s.id %}" class="btn btn-danger">Eliminar</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table><br>
  </div><br><br>

  
 


{% endblock %}

PawCare-1/templates/administracion/servicioCrear.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

 <div class="content">
    <div class="col-md-4">
        <a href="{% url 'users_app:servicios_admin'  %}"> Volver</a>
    </div>
</div> 

<div class="container">
    <div class="row">
        <h2>Ingresar Servicio</h2> 
    </div>
    <br>

        <div class="row">
            <form method="POST" action="#" id="formulario" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.id.label }}
                    {{ form.id }}
                </div>
                 
                <div class="form-group">
                    {{ form.nombre.label }}
                    {{ form.nombre }}
                </div>

                <div class="form-group">
                    {{ form.informacion.label }}
                    {{ form.informacion }}
                </div>

                <br>
                <div class="row">
                    <div class="col-md">

                        <input type="submit" class="btn btn-primary" value="Crear">
                        <input type="reset" class="btn btn-danger" value="Limpiar">
                        {% comment %} <a href="{% url 'admin_app:colaboradores_admin' form.id %}" class="btn btn-info">Volver</a> {% endcomment %}
                        
                    </div>
                </div>
                
            </form>
        </div>
</div> <br><br>
{% endblock %}

PawCare-1/templates/administracion/servicioModificar.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<br>
{% comment %} <div class="content">
    <div class="col-md-4">
        <a href="{% url 'admin_app:colaboradores_admin_s' form.id %}"> Volver</a>
    </div>
</div> {% endcomment %}

<div class="container">
    <div class="row">
        <h2>Modificar Servicio</h2> 
    </div>
    <br>

        <div class="row">
            <form method="POST" action="#" id="formulario" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.id.label }}
                    {{ form.id }}
                </div>
                 
                <div class="form-group">
                    {{ form.nombre.label }}
                    {{ form.nombre }}
                </div>

                <div class="form-group">
                    {{ form.informacion.label }}
                    {{ form.informacion }}
                </div>




                <br>
                <div class="row">
                    <div class="col-md">

                        <input type="submit" class="btn btn-primary" value="Modificar">
                        {% comment %} <a href="{% url 'admin_app:colaboradores_admin' id %}" class="btn btn-info">Volver</a> {% endcomment %}
                        
                    </div>
                </div>
                
            </form>
        </div>
</div> <br><br>
{% endblock %}

PawCare-1/templates/administracion/user.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">
<br>
<div class="container">
    <h2 class="titulo">Lista de Usuarios</h2><br><br>
    <table class="table"> <br>
        <thead>
            <tr>
                <th>identificador</th>
                <th>Nombre de Usuario</th>
                <th>Correo electronico</th>
                <th>Rut</th>
                <th>Nombre</th>
                <th>Apellido</th> 
                <th>Telefono</th> 
                <th>Tipo de usuario</th> 
                <th>Cuenta Activa</th>   
  
            </tr>
        </thead>
        <tbody>
            {% for user in lista_user %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username}}</td>
                <td>{{user.email}}</td>
                <td>{{user.rut}}</td>
                <td>{{user.nombres}}</td>
                <td>{{user.apellidos}}</td>
                <td>{{user.telefono}}</td>
                <td>{{user.categoria}}</td>
                <td>{{user.is_active}}</td>
                {% comment %} <td><a href="{% url 'users_app:user_modificar' user.id %}" class="btn btn-primary  btn-info btn-info-hover">Modificar</a></td> {% endcomment %}
            </tr>
            {% endfor %}
        </tbody>
    </table><br>
  </div><br><br>

  
 


{% endblock %}