PawCare-1/PawCare/urls.py
from django.contrib import admin
from django.urls import path ,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.views import HomeView,ColaboradoresView,SomosView,ServicioView
from applications.users.views import UserRegisterView
from applications.users.urls import auth_views 
from applications.users.forms import MySetPasswordForm



urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.users.urls')),

    re_path('', include('applications.home.urls')),

    re_path('', include('applications.administracion.urls')),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('users/',include('applications.users.urls',namespace='users')),
    # path('administracion/',include('applications.administracion.urls',namespace='administracion')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PawCare-1/applications/administracion/urls.py
from django.urls import path
from .views import *

app_name = "admin_app"

urlpatterns = [
    path('colab/', ListColaboradores.as_view(),name='colaboradores'),
    path('list_colab_admin/', ListColaboradores_admin.as_view(), name='colaboradores_admin'),
    path('list_colab_admin/<id>', ListColaboradores2_admin.as_view(), name='colaboradores_admin_s'),
    path('crear_colaborador/',AddColaboradores_admin.as_view(), name='crear_colaborador'),
    path('colaborador_modificar/<int:pk>', ModificarColab_admin.as_view(),name='colaborador_modificar'),
    

]

PawCare-1/applications/home/urls.py
from django.urls import path
from .views import *

app_name = "home_app"

urlpatterns = [
    path('',HomeView.as_view(),name='home',),
    path('colaboradores/',ColaboradoresView.as_view(),name='colaboradores',),
    path('servicios/',ServicioView.as_view(),name='servicios',),
    path('somos/',SomosView.as_view(),name='somos',),

    path('base/',BaseView.as_view(),name='base',),


]

PawCare-1/applications/users/urls.py
from django.urls import path


from django.contrib.auth import views as auth_views
from .views import *

from .forms import UserPasswordResetForm
from .views import View
from . import views
app_name ="users_app"


urlpatterns = [
    path('registro/', UserRegisterView.as_view(),name='user_register'),
    path('login/', LoginUser.as_view(),name='user_login'),
    path('logout/', LogoutView.as_view(),name='user_logout'),
    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),
    path('users/<username>', PerfilDetailView.as_view(),name='profile'),
    path('calendario/',CalendarioView.as_view(), name= 'calendario'),
    path('horas/',Addhoras.as_view(), name= 'horas'),
    path('list_mascota/', ListMascotas.as_view(), name='mascota'),
    path('list_mascota/<id>', ListMascotas2.as_view(), name='mascota'),
    path('crear_mascota/',AddMascota.as_view(), name='crear_mascota'),
    path('mascota_modificar/<int:pk>', ModificarMascota.as_view(),name='mascota_modificar'),
    path('mascota_eliminar/<int:pk>', MascotaDeleteView.as_view(),name='mascota_eliminar'),
    path('update/<int:pk>', PerfilUpdateView.as_view(),name='update'),

    path('list_horas/', ListCronogramaDisponibles.as_view(), name='horaseliminar'),
    path('cronograma_eliminar/<int:pk>', CronogramaDeleteView.as_view(),name='cronograma_eliminar'),

    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),

  

    path('servicios/<int:id>', ListCuidadores3.as_view(),name='cuidadores3'),
    
    path('servicios/<id>', ReservaRegisterView.as_view(),name='cuidadores3'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', form_class=UserPasswordResetForm,html_email_template_name ='users/password_reset_email.html'), name='password_reset'),
    path('api/mascota/por-usuario/', ListMascotaUser.as_view(),name='mascota-mascota-by-user'),

    path('vista_reserva/',ClienteResevarView.as_view(), name= 'vista_reserva'),

    path('list_user_admin/', ListUser.as_view(), name='usuarios_admin'),
    path('list_user_admin/<id>', ListUser2.as_view(), name='usuarios_admin_s'),
    path('user_modificar/<int:pk>', ModificarUser_admin.as_view(),name='user_modificar'),


    path('list_servicio_admin/', ListServicios.as_view(), name='servicios_admin'),
    path('list_servicio_admin/<id>', ListServicios2_admin.as_view(), name='servicios_admin_s'),
    path('crear_servicios/',AddServicios_admin.as_view(), name='crear_servicio'),
    path('servicio_modificar/<int:pk>', ModificarServicio_admin.as_view(),name='servicio_modificar'),
    path('servicio_eliminar/<int:pk>', ServicioDeleteView.as_view(),name='servicio_eliminar'),

    path('list_especie_admin/', ListEspecies.as_view(), name='especie_admin'),
    path('list_especie_admin/<id>', ListEspecies2_admin.as_view(), name='especie_admin_s'),
    path('crear_especie/',AddEspecies_admin.as_view(), name='crear_especie'),
    path('especie_modificar/<int:pk>', ModificarEspecie_admin.as_view(),name='especie_modificar'),
    path('especie_eliminar/<int:pk>', EspecieDeleteView.as_view(),name='especie_eliminar'),

    path('reservar_cuidador/<int:cronograma_id>', views.reservar_cuidador, name='reservar_cuidador'),
    
    path('list_horas_user/', HorasporUserList.as_view(), name='horas_user'),

    path('list_horas_realizadas_user/', HorasRealizadasporUserList.as_view(), name='horas_user_realizadas'), #esta

    path('cancelar_cuidador/<int:idReserva>', views.cancelar_cuidador, name='cancelar_cuidador'),
    path('finalizar_reserva/<int:idReserva>', views.finalizar_reserva, name='finalizar_reserva'),
    #path('rating_modal/', views.rating_modal , name='rating_modal'),
    path('rating_modal/', Calificacion.as_view() , name='rating_modal'),
    path('finalizar_reserva/<int:idReserva>/', views.finalizar_reserva, name='finalizar_reserva'),

    path('guardar_calificacion/', views.guardar_calificacion, name='guardar_calificacion'),
    #path('calcular_promedio_calificacion/', views.calcular_promedio_calificacion, name='calcular_promedio_calificacion'),
]

PawCare-1/applications/home/models.py
from django.db import models

# Create your models here.

PawCare-1/applications/home/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    CreateView
) 
# Create your views here.

class HomeView(TemplateView):
    template_name = 'home/home.html'

class ColaboradoresView(TemplateView):
    template_name = 'home/colab.html'

class ServicioView(LoginRequiredMixin,TemplateView):
    template_name = 'home/servicios.html'
    # login_url = reverse_lazy('users_app:user_login')

class SomosView(TemplateView):
    template_name = 'home/somos.html'

class BaseView(CreateView):
    template_name='base.html'

PawCare-1/templates/home/colab.html
{% extends 'base.html' %}

{% block content %} 
{% load static %}
<link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet"> 

<br>
<div>
    <div>
        <h1 class="titulo">Colaboradores</h1>
    </div>


    {% if user.is_authenticated %}
    {% else %}
        <center><a class="btn btn-danger" href="{% url 'users_app:user_register' %}">Registrarte para obtener descuentos</a></center>
    {% endif %}
    

        
   
    <hr>
    <!--Tarjetas-->
    <div class="container ">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for c in lista_colaboradores %}
            <div class="col">
                <div class="card">
                    {% if c.image %}
                    <img class="tarjeta-colab" src="{{c.image.url}}" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        <center><h1>{{c.title}}</h1></center>
                        <br>
                        <strong class="card-text"><h5>Quienes Somos:</h5></strong>
                        {{c.content}}

                        <br> <br>
                        
                        {% if user.is_authenticated %}
                        <div>
                            <strong class="card-text">Codigo de descuento:</strong>
                            {{c.descuento}}
                        </div>
                        {% else %}

<!--                        <center><a class="btn btn-danger" href="{% url 'users_app:user_register' %}">Registrarte para obtener descuentos</a></center>  -->
                        {% endif %}

                        <br>
                        <center><a class="btn btn-primary btn-info btn-info-hover" href="{{c.url}}"target="_blank">Visita Nuestra pagina</a></center>
                    </div>
                </div>
            </div>
            {% empty %}
                  
            <div class="container">
              <h3>No hay Colaboradores registrados</h3>
            </div> 
            {% endfor %}
        </div>
       
    </div>

</div>
<br>




{% endblock %}

PawCare-1/templates/home/error_404.html
{% extends 'base.html' %}

{% block content %} 
{% load static %}

<div>
<img src="{% static 'img/404.png' %}" >
</div>
<!--style=" width: auto; height: 100px; margin-left: 20px;"-->
{% endblock %}

PawCare-1/templates/home/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %} 
<link href="{% static 'css/home.css' %}" type="text/css" rel="stylesheet">

<!-- Carrusel-->
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="5000">
        <img src="{% static 'img/slider1.jpg' %}" class="d-block w-100" alt="50">
        <div class="carousel-caption d-none d-md-block">
          
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
        <img src="{% static 'img/slider2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
        <img src="{% static 'img/slider3.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <!-- Fin Carrusel-->

  <br>
  <div class="Sub1">Ultima información</div>
  <hr>
  <!--Tarjetas-->
   <div class="grid-container">
    <div class="grid-item">
        <div class="card" >
          <a href="{% url 'admin_app:colaboradores' %}">
            <img class="card-img-top imagen-carta" src="{% static 'img/card1.jpg' %}" alt="Card image cap">
          </a>
            <div class="card-body">
              <p class="titulo-home">La organización animalista Peludos</p>
            <p class="card-text texto">Nuestros colaboradores de la organización animalista peludos invitan a informar sobre la presencia de animales
              en situacion de calle para poder darles un albergue, ya que se ha informado que este invierno sera uno de los mas duros del ultimo tiempo.
            </p>
            </div>
        </div>
    </div>
    <div class="grid-item">
        <div class="card" >
          <a href="{% url 'admin_app:colaboradores' %}">
            <img class="card-img-top imagen-carta"src="{% static 'img/card2.jpeg' %}" alt="Card image cap">
          </a>
            <div class="card-body">
              <p class="titulo-home">La campaña por adoptar aumenta este mes </p>
            <p class="card-text texto">La campaña 'No Compres ¡Adopta!' ha sido un exito, sumate. ¿Como hacerlo? Dirigete a tu albergue mas cercano y realiza la adopción
              de una mascota.</p>
            </div>
        </div>
    </div>
    <div class="grid-item">
        <div class="card" >
            <a href="{% url 'home_app:servicios' %}">
              <img class="card-img-top imagen-carta" src="{% static 'img/card3.jpg' %}" alt="Card image cap">
            </a>
            <div class="card-body">
              <p class="titulo-home">Al solicitar algun servicio ayudas a miles de animales</p>
            <p class="card-text texto">Por cada vez que hagas uso de servicios en PawCare nosotros donaremos 10% del coste total del servicio a fundaciones animalistas y albergues de acogida
              de animales.</p>
            </div>
        </div>
    </div>   
  </div>
  <!--Fin Tarjetas-->

{% endblock %}

PawCare-1/templates/home/servicios.html
{% extends 'base.html' %}

{% block content %} 
{% load static %}

<link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/tarjetacuidador.css' %}" type="text/css" rel="stylesheet">
<script  src="{% static 'js/calificacion.js' %} "></script> 
<script  src="{% static 'js/reserva.js' %} "></script> 

<br>
<div>
    <div>
        <h1 class="titulo">Cuidadores</h1>
    </div>
    <hr>
    <!--Tarjetas-->
    <div class="container ">
        <div class="row">

        </div>

      <form method="GET" > {%csrf_token%}


        
       <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-primary active">
          <button class="btn btn-info" type="submit" id="kword" name="kword" value="" >Todos</button>
        </label>
        <label class="btn btn-warning active">
          <button class="btn btn-info" type="submit" id="kword" name="kword" value="Cuidado a domicilio" >Cuidado a domicilio</button>
        </label>
        <label class="btn btn-warning">
          <button class="btn btn-info" type="submit" id="kword" name="kword" value="Peluqueria" >Peluqueria</button>
        </label>
        <label class="btn btn-warning">
          <button class="btn btn-info" type="submit" id="kword" name="kword" value="Transporte de Mascota" >Transporte de Mascota</button>
        </label>
      </div> 

    </form>
    <br>
    <p>

      <!-- <form method="GET" > {%csrf_token%}
        <input class""  type="text" id="nombre" name="nombre" placeholder="Ingrese nombre">
        <button type="submit">Buscar</button>
      </form> -->

      <form method="GET" > {%csrf_token%}
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingrese nombre" aria-label="Recipient's username" aria-describedby="button-addon2">
          <button class="btn btn-outline-info" type="submit" id="button-addon2">Buscar</button>
        </div>
      </form>
  </p>
      <br>
        
        <div class="row row-cols-2 row-cols-md-4 g-4">
            {% for c in lista_cuidadores %}

            <div class="col" width="240px">
                <div class="card" width="240px">
                    <img class="card-img-top" src="{{c.profile.picture.url}}" width="240px">
                    <div class="card-body">
                        <h5>{{c.nombres}} {{c.apellidos}}</h5>
                        <p class="card-text">{{c.profile.descripcion}}</p>
                        {% for servicios in c.profile.servicios.all %}
                        <span class="badge bg-primary">{{ servicios.nombre  | upper }}</span>
                      {% endfor %} 

                      {% for cronograma in c.cronograma.all %}
<!--                      <span class="badge bg-primary">{{ cronograma.fechaReserva  | upper }}</span>
                      <span class="badge bg-primary">{{ cronograma.horas  | upper }}</span> 
                      <table class="table">
                        <thead class="thead-dark">
                          <tr>
                            <th scope="col">Fecha:</th>
                            <th scope="col">{{ cronograma.fechaReserva  | upper }}</th>

                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="row">Horas:</th>
                            <td>{{ cronograma.horas.horaInicio  | upper }}-{{ cronograma.horas.horaFin  | upper }}</td>

                          </tr>
                        </table> -->
                      {% endfor %}



                        <div>{{c.promediocalificacion}}</div>
                        <div id="calificacion_estrellas">
                            <script>
                                document.write(generarEstrellas({{c.promediocalificacion}}));
                            </script>
                        </div>
                        <br>
                        {%if request.user.categoria == '1' %}
             <!--           <div>
                            <button type="button" class="btn btn-primary" onclick="abrir_modal3('{% url 'users_app:vista_reserva'  %}');">Reservar</button>
                            
                        </div>
                        <br> -->
                        <div>
                            <a type="button" class="btn btn-primary btn-info btn-info-hover" href="{% url 'users_app:cuidadores3' c.id %}">Reservar</a>
                        </div> 
                        {% endif%}


                    </div>
                </div>
                <div id="reservar"></div>
            </div>
            {% empty %}
                  
            <div class="container">
              <h3>No hay Cuidadores en este momento</h3>
            </div> 
            {% endfor %}
        </div>
        
    </div>

</div>
<br>

{% endblock %}

PawCare-1/templates/home/somos.html
{% extends 'base.html' %}
{% load static %}

{% block content %} 
<link href="{% static 'css/somos.css' %}" type="text/css" rel="stylesheet">
<br>
<div class="contenido">
<div class="grid-container container-fluid">
  <div class="grid-item ">
    <h1 class="titulo">¿Quienes Somos?</h1>
    <br>
    <p>Somos una organización que se especializa en la comercialización del mejor cuidado para mascotas.</p>
    <p>Somos una organización que se fundo en 2023 con la idea de que las mascotas necesitan el mejor cuidado posible y no siempre estan sus dueños disponibles para ello.</p>
    <p>Contamos con con la colaboracion con multiples organizaciónes y cuidadores que comparten nuestro objetivo</p>
  </div>
  <div class="grid-item">
    <img src="{% static 'img/quienessomos1.jpg' %}" class="imagensomos1 img-fluid ">
  </div>
</div>
<hr>
<div class="grid-container container-fluid">
  <div class="grid-item">
    <img src="{% static 'img/quienessomos2.jpeg' %}" class="imagensomos2 img-fluid">  
  </div>  
  <div class="grid-item ">
    <h1 class="titulo">Nuestra Misión</h1>
    <br>
    <p>Nuestra misión como organización es que su mascota obtenga el mejor trato y cuidado posible.</p>
    <p>Por eso contamos con cientos de cuidadores que trabajan bajo nuestro sistema de reservas.</p>
  </div>
</div>
<br>
</div>

{% endblock %}