PawCare-1/PawCare/urls.py
from django.contrib import admin
from django.urls import path ,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.views import HomeView,ColaboradoresView,SomosView,ServicioView
from applications.users.views import UserRegisterView
from applications.users.urls import auth_views 
from applications.users.forms import MySetPasswordForm



urlpatterns = [
    path('admin/', admin.site.urls),

    re_path('', include('applications.users.urls')),

    re_path('', include('applications.home.urls')),

    re_path('', include('applications.administracion.urls')),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('users/',include('applications.users.urls',namespace='users')),
    # path('administracion/',include('applications.administracion.urls',namespace='administracion')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PawCare-1/applications/administracion/urls.py
from django.urls import path
from .views import *

app_name = "admin_app"

urlpatterns = [
    path('colab/', ListColaboradores.as_view(),name='colaboradores'),
    path('list_colab_admin/', ListColaboradores_admin.as_view(), name='colaboradores_admin'),
    path('list_colab_admin/<id>', ListColaboradores2_admin.as_view(), name='colaboradores_admin_s'),
    path('crear_colaborador/',AddColaboradores_admin.as_view(), name='crear_colaborador'),
    path('colaborador_modificar/<int:pk>', ModificarColab_admin.as_view(),name='colaborador_modificar'),
    

]

PawCare-1/applications/users/urls.py
from django.urls import path


from django.contrib.auth import views as auth_views
from .views import *

from .forms import UserPasswordResetForm
from .views import View
from . import views
app_name ="users_app"


urlpatterns = [
    path('registro/', UserRegisterView.as_view(),name='user_register'),
    path('login/', LoginUser.as_view(),name='user_login'),
    path('logout/', LogoutView.as_view(),name='user_logout'),
    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),
    path('users/<username>', PerfilDetailView.as_view(),name='profile'),
    path('calendario/',CalendarioView.as_view(), name= 'calendario'),
    path('horas/',Addhoras.as_view(), name= 'horas'),
    path('list_mascota/', ListMascotas.as_view(), name='mascota'),
    path('list_mascota/<id>', ListMascotas2.as_view(), name='mascota'),
    path('crear_mascota/',AddMascota.as_view(), name='crear_mascota'),
    path('mascota_modificar/<int:pk>', ModificarMascota.as_view(),name='mascota_modificar'),
    path('mascota_eliminar/<int:pk>', MascotaDeleteView.as_view(),name='mascota_eliminar'),
    path('update/<int:pk>', PerfilUpdateView.as_view(),name='update'),

    path('list_horas/', ListCronogramaDisponibles.as_view(), name='horaseliminar'),
    path('cronograma_eliminar/<int:pk>', CronogramaDeleteView.as_view(),name='cronograma_eliminar'),

    path('servicios/', ListCuidadores.as_view(),name='cuidadores'),

  

    path('servicios/<int:id>', ListCuidadores3.as_view(),name='cuidadores3'),
    
    path('servicios/<id>', ReservaRegisterView.as_view(),name='cuidadores3'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', form_class=UserPasswordResetForm,html_email_template_name ='users/password_reset_email.html'), name='password_reset'),
    path('api/mascota/por-usuario/', ListMascotaUser.as_view(),name='mascota-mascota-by-user'),

    path('vista_reserva/',ClienteResevarView.as_view(), name= 'vista_reserva'),

    path('list_user_admin/', ListUser.as_view(), name='usuarios_admin'),
    path('list_user_admin/<id>', ListUser2.as_view(), name='usuarios_admin_s'),
    path('user_modificar/<int:pk>', ModificarUser_admin.as_view(),name='user_modificar'),


    path('list_servicio_admin/', ListServicios.as_view(), name='servicios_admin'),
    path('list_servicio_admin/<id>', ListServicios2_admin.as_view(), name='servicios_admin_s'),
    path('crear_servicios/',AddServicios_admin.as_view(), name='crear_servicio'),
    path('servicio_modificar/<int:pk>', ModificarServicio_admin.as_view(),name='servicio_modificar'),
    path('servicio_eliminar/<int:pk>', ServicioDeleteView.as_view(),name='servicio_eliminar'),

    path('list_especie_admin/', ListEspecies.as_view(), name='especie_admin'),
    path('list_especie_admin/<id>', ListEspecies2_admin.as_view(), name='especie_admin_s'),
    path('crear_especie/',AddEspecies_admin.as_view(), name='crear_especie'),
    path('especie_modificar/<int:pk>', ModificarEspecie_admin.as_view(),name='especie_modificar'),
    path('especie_eliminar/<int:pk>', EspecieDeleteView.as_view(),name='especie_eliminar'),

    path('reservar_cuidador/<int:cronograma_id>', views.reservar_cuidador, name='reservar_cuidador'),
    
    path('list_horas_user/', HorasporUserList.as_view(), name='horas_user'),

    path('list_horas_realizadas_user/', HorasRealizadasporUserList.as_view(), name='horas_user_realizadas'), #esta

    path('cancelar_cuidador/<int:idReserva>', views.cancelar_cuidador, name='cancelar_cuidador'),
    path('finalizar_reserva/<int:idReserva>', views.finalizar_reserva, name='finalizar_reserva'),
    #path('rating_modal/', views.rating_modal , name='rating_modal'),
    path('rating_modal/', Calificacion.as_view() , name='rating_modal'),
    path('finalizar_reserva/<int:idReserva>/', views.finalizar_reserva, name='finalizar_reserva'),

    path('guardar_calificacion/', views.guardar_calificacion, name='guardar_calificacion'),
    #path('calcular_promedio_calificacion/', views.calcular_promedio_calificacion, name='calcular_promedio_calificacion'),
]

PawCare-1/applications/users/models.py
from datetime import date
import datetime
from django.db import models
import os
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser ,PermissionsMixin
from django.db.models.signals import post_save 

from .managers import UserManager ,MascotaManager,HorasManager,HorasSolicitadasManager

from applications.categoria.models import Categoria

# Create your models here.


class Region(models.Model):
    id=models.AutoField(primary_key=True)
    nombre= models.CharField(max_length=80, unique= True,verbose_name='Region')

    def __str__(self):
        return self.nombre
    

class Comuna(models.Model):
    id=models.AutoField(primary_key=True)
    nombre= models.CharField(max_length=80, unique= True,verbose_name='Comuna')

    def __str__(self):
        return self.nombre

class User (AbstractBaseUser, PermissionsMixin, models.Model ):

    # TIPO DE USUARIOS
    CLIENTE = '1' 
    CUIDADOR = '2'
    ADMINISTRADOR= '3'
    TIPOUSER_CHOICES = [
        (CLIENTE, 'Cliente'),
        (CUIDADOR, 'Cuidador'),
        (ADMINISTRADOR, 'Administrador'),
    ]

    username = models.CharField(max_length=16, unique=True)
    email = models.EmailField()
    rut = models.CharField(max_length=9, null= True)
    nombres= models.CharField(max_length=100)
    apellidos= models.CharField(max_length=100)
    telefono= models.CharField(max_length=9,null = True)
    # tipodeusuario=models.CharField(max_length=2,choices=TIPOUSER_CHOICES,null=True,default=2)
    # categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE,null=True)
    categoria = models.CharField(max_length=2,choices=TIPOUSER_CHOICES,null=True,default=1)
    promediocalificacion = models.DecimalField(max_digits=2, decimal_places=1, null=True,default=0)

    region =  models.ForeignKey(Region,on_delete=models.CASCADE,related_name='Region',null=True,default=1)
    comuna =  models.ForeignKey(Comuna,on_delete=models.CASCADE,related_name='Comuna',null=True,default=1)
    direccion = models.CharField(max_length=100,verbose_name='Direccion',null=True)
 
    #
    is_staff = models.BooleanField(default=False) #para especificar si el usuario es administrador
    is_active= models.BooleanField(default=True)   
    USERNAME_FIELD ='username'

    REQUIRED_FIELDS = ['email']

    objects = UserManager()
    def __str__(self):
        return str(self.id)+"-"+str(self.username) 

    def get_short_name(self):
        return self.username
    def get_full_name(self):
        return self.nombres+" "+self.apellidos

#Modelo de Tipos de servicios

# Agregar una columna de valor x servicio que vamos a definir nosotros

class Servicio(models.Model):
    id= models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=80, unique= True,verbose_name='Tipo de servicio')
    informacion=models.TextField(max_length=2000,blank=False,null=True, default='Sin description')
    estado = models.BooleanField('Estado', default = True)

   

    class Meta:
        verbose_name = 'servicio'
        verbose_name_plural ='servicios'
        ordering = ['id']
    def __str__(self):
        return self.nombre 

#Modelo perfil
def user_directory_path_profile(instance, filename):
    profile_picture_name = 'users/{0}/profile.jpg'.format(instance.user.username)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_picture_name)

    if os.path.exists(full_path):
        os.remove(full_path)

    return profile_picture_name

class Profile(models.Model):
    id= models.AutoField(primary_key=True)
    user= models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    # picture = models.ImageField(default='users/user_default_profile.png', upload_to=user_directory_path_profile)
    picture = models.ImageField(default='users/perfil_defecto.jpg', upload_to=user_directory_path_profile)
    descripcion= models.TextField(max_length=2000,null=True,blank=True, default='Ingresa una descripcion')
    # servicios=models.ForeignKey(Tservicio,on_delete=models.CASCADE,null=True)
    servicios=models.ManyToManyField(Servicio,related_name='servicios',verbose_name='Tipos de servicios')
    def __str__(self):
        return self.user.username
    

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

# created profile
post_save.connect(create_user_profile, sender=User)
# save created profile
post_save.connect(save_user_profile, sender=User)


class EstadoReserva(models.Model):
    id=models.AutoField(primary_key=True)
    reservaEstado= models.CharField(max_length=15)
    def __str__(self):
        return  str(self.reservaEstado) 
    #str(self.id) + "-" +
class Hora(models.Model):
    id=models.AutoField(primary_key=True)
    horaInicio=models.TimeField(verbose_name='inicio')
    horaFin=models.TimeField(null=True,verbose_name='fin')
    # estado= models.ForeignKey(EstadoReserva,on_delete=models.CASCADE,related_name='Estado',null=True,default=1)

    def __str__(self):
        return str(self.horaInicio) + " - " +str(self.horaFin) 
    # str(self.id) + " - " +
class Cronograma(models.Model):
     id= models.AutoField(primary_key=True)
     user= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='cronograma', null=True)
     fechaReserva=models.DateField('Dia',null=True,blank=True,default=date.today)
    #  horas=models.ManyToManyField(Hora,related_name='horas',verbose_name='Horas a seleccionar')
     horas=models.ForeignKey(Hora,on_delete=models.CASCADE,related_name='horas',verbose_name='Hora a seleccionar',null=True, default=2)
     estado= models.ForeignKey(EstadoReserva,on_delete=models.CASCADE,related_name='Estado',null=True,default=1)
    
     objects = HorasManager()

     def __str__(self):
        return str(self.fechaReserva) +"/"+ str(self.user)+"/"+ str(self.estado)
     


     

# def create_user_cronograma(sender, instance, created, **kwargs):
#     if created:
#         Cronograma.objects.create(user=instance)


# def save_user_cronograma(sender, instance, **kwargs):
#     instance.cronograma.save()

# # created profile
# post_save.connect(create_user_cronograma, sender=User)
# # save created profile
# post_save.connect(save_user_cronograma, sender=User)

    

#Reserva
#Esta tabla debe ser llanda por nostros
# class EstadoReserva(models.Model):
#     id=models.AutoField(primary_key=True)
#     reservaEstado= models.CharField(max_length=15)
#     def __str__(self):
#         return self.reservaEstado 
 
# class DiaReserva(models.Model):
#     id=models.AutoField(primary_key=True)
#     fechaReserva=models.DateField('Dia',null=True,blank=True,default=date.today)
#     horaInicio=models.TimeField(verbose_name='inicio')
#     horaFin=models.TimeField(null=True,verbose_name='fin')
#     estado= models.ForeignKey(EstadoReserva,on_delete=models.CASCADE,related_name='Estado',null=True)

#     objects = HoraManager()

#     def __str__(self):
#         return str(self.fechaReserva) + "/ " + str(self.horaInicio) + "-"+ str(self.horaFin) 


# class Hora(models.Model):
#     id=models.AutoField(primary_key=True)
#     horas=models.TimeField()
    



#class Calificacion(models.Model):
 #   id=models.AutoField(primary_key=True)
  #  rating=models.IntegerField()




#MASCOTAS
#Esta tabla debe ser llenada por nosotros
class Especies(models.Model):
    id= models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=80, unique= True,verbose_name='Tipo de mascota')


    class Meta:
        verbose_name = 'especie'
        verbose_name_plural ='especies'
        ordering = ['id']
    def __str__(self):
        return self.nombre 



class Mascota(models.Model):

    IS_PUBLISHED_CHOICES = [
        ('No','No'), 
        ('Si', 'Si')]
    
    id= models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='Dueño',null=True,blank=True)
    nombre_de_mascota = models.CharField(max_length=50, blank= True, null=True)
    chip= models.CharField(max_length=2 ,verbose_name='Chip', choices=IS_PUBLISHED_CHOICES, default='NO')
    n_chip= models.CharField(max_length=50, blank= True, null=True, default='No poose')
    image = models.ImageField(upload_to='mascotas' ,null=True, blank=True, verbose_name='Imagen del la Mascota')
    descripccion = models.TextField(verbose_name='Descripccion del la mascota')
    especies=models.ForeignKey(Especies,related_name='especies',verbose_name='Tipos de mascota',on_delete=models.CASCADE,null=True,default=1)

   

    class Meta:
        verbose_name = 'mascota'
        verbose_name_plural ='mascotas'
        ordering = ['id']

    objects = MascotaManager()
    
    def __str__(self):
        return  str(self.nombre_de_mascota)
    #+"/"+str(self.user)

                                         
class ReservaCliente(models.Model):
    id= models.AutoField(primary_key=True)
    clienteusername=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='Usuario',null=True,blank=True)
    idCronograma = models.ForeignKey(Cronograma, on_delete=models.CASCADE,related_name='reservas',null=True,blank=True)
    correocuidaor=models.CharField(max_length=100,null=True, blank=True)
    correocliente=models.CharField(max_length=100,null=True, blank=True)
    idCuidador=models.CharField(max_length=100,null=True, blank=True)
    idCliente=models.CharField(max_length=100, null=True, blank=True)
    nombreCliente=models.CharField(max_length=100, null=True, blank=True)
    nombreCuidador=models.CharField(max_length=100, null=True, blank=True)
    fechareserva=models.CharField( max_length=100,null=True, blank=True)
    horasInicio=models.CharField(max_length=100, null=True, blank=True)
    horasFin=models.CharField( max_length=100,null=True, blank=True)
    servicios = models.TextField(null=True, blank=True)

PawCare-1/templates/users/Mascota.html
<div class= "modal fade" id="edicion" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class= "modal-title">Editar Mascota</h2>
                <button class="close" type="button" data-dismiss ="modal" aria-label="Close">
                    <span arial-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <form method="POST" action="#" id="formulario" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.image.label }}
                            {{ form.image }}
                        </div>
        
                        <div class="form-group">
                            {{ form.nombre_de_mascota.label }}
                            {{ form.nombre_de_mascota }}
                        </div>
                        
        
                        <div class="form-group">
                            {{ form.descripccion.label }}
                            {{ form.descripccion }}
                        </div>
        
                        <div class="form-group">
                        {{ form.chip.label }}
                        {{ form.chip }}
                    </div>
                    <div class="form-group">
                        {{ form.n_chip.label }}
                        {{ form.n_chip }}
                    </div>
                    <div class="form-group">
                        {{ form.especies.label }} 
                        {{ form.especies }}
                    </div> 
        
        
                        <br>
                        <div class="row">
                            <div class="col-md">
        
                                {% comment %} <input type="submit" class="btn btn-primary" value="Modificar"> {% endcomment %}
                                {% comment %} <a href="{% url 'admin_app:colaboradores_admin' id %}" class="btn btn-info">Volver</a> {% endcomment %}
                                
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div> <!-- hasta va el formulario -->

            <div class="modal-footer"> 
                <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary" type="submit" data-dismiss="modal">Confirmar</button>
            </div>

        </div>

    </div>
</div>

PawCare-1/templates/users/mascota_confirm_delete.html
<div class="modal fade" id="myModalDelete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmar Acción</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'users_app:mascota_eliminar' object.id %}" method="POST">
                    {% csrf_token %}
            
                    <div class="mt-2">
                        
                            <div class="card-header text-center" style="font-size: 30px;">Borrar Mascota</div>
                            <div class="card-body">
                                <br>
                                
                                <p class="card-text">Está seguro de querer eliminar a: "<strong>{{ mascota }}</strong>"</p>
            
                                <strong>ATENCION, ESTA ACCIÓN NO SE PODRÁ DESHACER</strong>
                                
                                <div class="text-center">
                                    <br>
                            
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                        <input class="btn btn-primary" type="submit" value="SI, BORRAR ">
                                    </div>

            
                                </div>
                            </div>
                        
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

PawCare-1/templates/users/registro.html
{% extends 'base.html' %}

{% block content %} 

{% load static %}

<link rel="stylesheet" href="{% static 'css/formulario.css' %}" >
<style>
    .bg{
        background-image: url("{% static 'img/fotopararegistro.png' %}");
        background-position: center center;
        width:100%;
        alt:100%;
        border-radius:5px;
    }
</style>



<div class="container w-100 bg-primary mt-5 rounded shadow">
    <div class="row align-item-stretch">
        <div class="col bg d-none d-lg-block rounded">
        </div>

        
        <div class="col bg-white p-20 rounded-end">
            <div class="text-end">
                <img src="{% static 'img/logoup.png' %}" width="78" alt="" >
            </div>
            <h2 class="fw-bold text-center pt5 mb-5">Registro de usuario</h2>


            <!-- {% if 'ok' in request.GET %} 
            <div class="alert alert-success" role="alert">
               Bienvenido tu Cuenta fue Creada con Exito 
               <span>
                   <a class="btn btn-sm btn-success" href="{% url 'users_app:user_login' %}" id="">Iniciar Sesion</a>
               </span>
           </div>
             {% endif %}  -->

            <form action="" method="POST" class="formulario" id="formulario" > 
                {% csrf_token %} 
                <!-- Grupo: Usuario -->
                <div class="formulario__grupo" id="grupo__username">
                    <label for="id_username" class="formulario__label">Nombre de usuario</label>
                    <div class="formulario__grupo-input">
                     <!--   <input type="text" class="formulario__input" name="usuario" id="usuario" placeholder="Gatito23"  > -->
                        {{ form.username }}
                        {% for e in  form.username.errors %}
                        <p style="color:red;">{{ e }}</p>
                      {% endfor %}

                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">El usuario tiene que ser de 4 a 16 dígitos y solo puede contener numeros, letras y guion bajo.</p>
                </div>

                <!-- Grupo: Correo Electronico -->
                <div class="formulario__grupo" id="grupo__email">
                    <label for="id_email" class="formulario__label">Correo Electrónico</label>
                    <div class="formulario__grupo-input">
                    <!--    <input type="email" class="formulario__input" name="correo" id="correo" placeholder="correo@correo.com" > -->
                        {{ form.email }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">El correo solo puede contener letras, numeros, puntos, guiones y guion bajo.</p>
                </div>
                <!-- Grupo: Rut -->
                <div class="formulario__grupo" id="grupo__rut">
                    <label for="id_rut" class="formulario__label">Rut</label>
                    <div class="formulario__grupo-input">
                    <!--    <input type="text" class="formulario__input" name="rut" id="rut" placeholder="11111111-1" > -->
                        {{ form.rut }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">El rut debe ser ingresado sin punto ni guion,si lleva una k remplazela por un 0.</p>
                </div>
    
                <!-- Grupo: Nombre -->
                <div class="formulario__grupo" id="grupo__nombres">
                    <label for="id_nombres" class="formulario__label">Nombre</label>
                    <div class="formulario__grupo-input">
                    <!--    <input type="text" class="formulario__input" name="nombre" id="nombre" placeholder="Ingresa tus nombres"  > -->
                        {{ form.nombres }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">Este campo solo permite letras en Mayusculas y minusculas.</p>
                </div>

                <!-- Grupo: Apellidos -->
                <div class="formulario__grupo" id="grupo__apellidos">
                    <label for="id_apellidos" class="formulario__label">Apellidos</label>
                    <div class="formulario__grupo-input">
                    <!--    <input type="text" class="formulario__input" name="apellido" id="apellido" placeholder="Ingresa tus apellidos"  > -->
                        {{ form.apellidos }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">Este campo solo permite letras Mayusculas y minusculas.</p>
                </div>

                <!-- Grupo: Teléfono -->
                <div class="formulario__grupo" id="grupo__telefono">
                    <label for="id_telefono" class="formulario__label">Teléfono</label>
                    <div class="formulario__grupo-input">
                        <!--<input type="text" class="formulario__input" name="telefono" id="telefono" placeholder="4491234567" >-->
                        {{ form.telefono }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">El telefono solo puede contener 9 dígitos.</p>
                </div>

                <!-- Grupo: Region -->
                <div class="formulario__grupo" id="grupo__region">
                    <label for="id_region" class="formulario__label">Ciudad</label>
                    <div class="formulario__grupo-input">
                        <!--<input type="text" class="formulario__input" name="telefono" id="telefono" placeholder="4491234567" >-->
                        {{ form.region }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error"></p>
                </div>

                <!-- Grupo: Comuna -->
                <div class="formulario__grupo" id="grupo__comuna">
                    <label for="id_comuna" class="formulario__label">Comuna</label>
                    <div class="formulario__grupo-input">
                        <!--<input type="text" class="formulario__input" name="telefono" id="telefono" placeholder="4491234567" >-->
                        {{ form.comuna }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error"></p>
                </div>

                <!-- Grupo: Direccion -->
                <div class="formulario__grupo" id="grupo__direccion">
                    <label for="id_direccion" class="formulario__label">Direccion</label>
                    <div class="formulario__grupo-input">
                        <!--<input type="text" class="formulario__input" name="telefono" id="telefono" placeholder="4491234567" >-->
                        {{ form.direccion }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">Debe Ingresar una direccion</p>
                </div>




                <!-- Grupo: Tipo de usuario -->

                <div class="formulario__grupo" id="grupo__tipousuario">
                    <label for="categoria" class="formulario__label">Selecciona el tipo de usuario</label>
                    <div class="formulario__grupo-input">
                        <!--<input type="text" class="formulario__input" name="telefono" id="telefono" placeholder="4491234567" >-->
                        {{ form.categoria }}
                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">Debes marcar una opcion.</p>
                </div>


    
                <!-- Grupo: Contraseña -->
                <div class="formulario__grupo" id="grupo__password1">
                    <label for="id_password1" class="formulario__label">Contraseña</label>
                    <div class="formulario__grupo-input">
                    <!--    <input type="password" class="formulario__input" name="password" id="password"  >-->
                        {{ form.password1 }}

                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">La contraseña tiene que ser de 4 a 12 dígitos.</p>
                </div>
    
                <!-- Grupo: Contraseña 2 -->
                <div class="formulario__grupo" id="grupo__password2">
                    <label for="id_password2" class="formulario__label">Repetir Contraseña</label>
                    <div class="formulario__grupo-input">
                    <!--<input type="password" class="formulario__input" name="password2" id="password2" > -->
                       {{ form.password2 }}
                       {% for e in  form.password2.errors %}
                       <p style="color:red;">{{ e }}</p>
                     {% endfor %}

                        <i class="formulario__validacion-estado fas fa-times-circle"></i>
                    </div>
                    <p class="formulario__input-error">Ambas contraseñas deben ser iguales.</p>
                </div>
    

    

    

    
                <div class="formulario__mensaje" id="formulario__mensaje">
                    <p><i class="fas fa-exclamation-triangle"></i> <b>Error:</b> Por favor rellena el formulario correctamente. </p>
                </div>
                <br>
                <div class="formulario__grupo formulario__grupo-btn-enviar">
                    <button type="submit" class="formulario__btn">Registrarse</button>
                    <br><br><br>
                    <p class="formulario__mensaje-exito" id="formulario__mensaje-exito">Formulario enviado exitosamente!</p>
                </div>
            </form>         
        </div>
    </div>
</div> 
<br>


<script src="{% static 'js/formulario.js'%}"></script>







{% endblock %}

PawCare-1/templates/users/reserva_confirmada.html
<div class="modal fade" id="MyModalConfirmarReserva" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Reserva</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
        </div>
    </div>
</div>